# Utiliser une image de base Golang
FROM golang:1.23-alpine

WORKDIR /app

# Installer Air pour le rechargement automatique
RUN go install github.com/air-verse/air@latest

# Installer migrate pour gérer les migrations
RUN go install -tags 'mysql' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

# Copier les fichiers go.mod et go.sum pour télécharger les dépendances
COPY go.mod go.sum ./
RUN go mod download

# Copier tout le code source
COPY . .

# Copier les fichiers de templates
COPY cmd/Presentation/Views /app/cmd/Presentation/Views

# S'assurer que le fichier .air.toml est copié
COPY .air.toml /app

# Lancer Air pour le rechargement automatique
CMD ["air", "-c", "/app/.air.toml"]

# Exposer le port sur lequel l'application écoute
EXPOSE 8080