version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: "Europe/Zurich"
    networks:
      - toolkit_go

  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./docker/web/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - toolkit_go

networks:
  toolkit_go:
    driver: bridge