# Utiliser une image de base Golang
FROM golang:1.22.6-alpine

WORKDIR /app

# Installer Air pour le rechargement automatique
RUN go install github.com/air-verse/air@latest

# Copier les fichiers go.mod et go.sum pour télécharger les dépendances
COPY cmd/admin/go.mod cmd/admin/go.sum ./
RUN go mod download

# Copier tout le code source de l'administration
COPY cmd/admin/ ./

# Lancer Air pour le rechargement automatique
CMD ["air", "-c", "/app/.air.toml"]

# Exposer le port sur lequel l'application écoute
EXPOSE 8080